#!/usr/bin/env python3
"""Restore task_directory.json after accidental overwrite."""
import json, os

tasks = [
    {
        "taskId": "agent-control-center-optimization",
        "title": "Agent Control Center 优化",
        "parentProjectId": "agent-control-center-optimization",
        "parentProjectName": "Agent Control Center 优化",
        "workspacePath": "F:\\1AI\\Agent control center\\projects\\archive\\Agent Control Center 优化",
        "status": "已完成",
        "phase": "Phase 7: 监控与文档（最终阶段）",
        "assignee": "",
        "updatedAt": "2026-06-26",
        "tags": ["Prometheus", "metrics", "API文档", "运维手册", "端口修复", "Agent Control Center", "最终归档"],
        "source": "projects_index",
        "hidden": False
    },
    {
        "taskId": "phase4-privacy-scan",
        "title": "Phase 4 — 隐私扫描集成",
        "parentProjectId": "phase4-privacy-scan",
        "parentProjectName": "Phase 4 — 隐私扫描集成",
        "workspacePath": "F:\\1AI\\Agent control center\\projects\\agent-evolution",
        "status": "已归档",
        "phase": "方案规划（三审含阻塞补充）→ 开发 → 返工 → README补充 → 运维验证 → 质量审计",
        "assignee": "",
        "updatedAt": "2026-06-30",
        "tags": ["Agent进化", "Phase 4", "隐私扫描", "敏感信息检测", "SHA256指纹", "appSecret"],
        "source": "projects_index",
        "hidden": False
    },
    {
        "taskId": "company-doc-review-20260710",
        "title": "芯智呈光公司资料整理与优化方案",
        "parentProjectId": "company-doc-review-20260710",
        "parentProjectName": "芯智呈光公司资料整理与优化方案",
        "workspacePath": "F:\\1AI\\Agent control center\\projects\\archive\\company-structure-review",
        "status": "已完成",
        "phase": "公司架构分析审计（返工闭环+已归档）",
        "assignee": "",
        "updatedAt": "2026-07-10",
        "tags": ["公司资料", "差异化发展战略", "公司架构", "协议文件", "分析报告"],
        "source": "projects_index",
        "hidden": False
    },
    {
        "taskId": "task-skill-upgrade-20260630",
        "title": "TASK-SKILL-UPGRADE-20260630",
        "parentProjectId": "task-skill-upgrade-20260630",
        "parentProjectName": "TASK-SKILL-UPGRADE-20260630",
        "workspacePath": "F:\\1AI\\Agent control center\\projects\\archive\\TASK-SKILL-UPGRADE-20260630",
        "status": "进行中",
        "phase": "独立任务",
        "assignee": "",
        "updatedAt": "2026-07-10T08:14:52.070339+00:00",
        "tags": [],
        "source": "filesystem",
        "hidden": False
    },
    {
        "taskId": "chip-startup-kpi-incentive",
        "title": "芯片初创公司管理层KPI激励方案",
        "parentProjectId": "chip-startup-kpi-incentive",
        "parentProjectName": "芯片初创公司管理层KPI激励方案",
        "workspacePath": "F:\\1AI\\Agent control center\\projects\\archive\\芯片初创公司管理层KPI激励方案",
        "status": "已完成",
        "phase": "Phase 3: CXO激励方案（含返工闭环）",
        "assignee": "",
        "updatedAt": "2026-06-29",
        "tags": ["KPI激励方案", "芯片初创公司", "CXO激励", "返工闭环", "五级阶梯", "Phase 3"],
        "source": "projects_index",
        "hidden": False
    },
    {
        "taskId": "config-center-knowledge-base",
        "title": "配置中心-本地知识库功能方案",
        "parentProjectId": "agent-control-center-optimization",
        "parentProjectName": "Agent Control Center 优化",
        "workspacePath": "F:\\1AI\\Agent control center",
        "status": "已完成",
        "phase": "方案规划（审计通过+已归档）",
        "assignee": "项目调度官",
        "updatedAt": "2026-07-10T16:33:00.000000+08:00",
        "tags": ["配置中心", "知识库", "本地方案", "防泄密", "Agent Control Center"],
        "source": "initiative",
        "hidden": False
    },
    {
        "taskId": "agent-evolution",
        "title": "agent-evolution",
        "parentProjectId": "agent-evolution",
        "parentProjectName": "agent-evolution",
        "workspacePath": "F:\\1AI\\Agent control center\\projects\\agent-evolution",
        "status": "进行中",
        "phase": "独立任务",
        "assignee": "",
        "updatedAt": "2026-07-13T05:50:57.223436+00:00",
        "tags": [],
        "source": "filesystem",
        "hidden": False
    },
    {
        "taskId": "company-structure-review",
        "title": "company-structure-review",
        "parentProjectId": "company-structure-review",
        "parentProjectName": "company-structure-review",
        "workspacePath": "F:\\1AI\\Agent control center\\projects\\archive\\company-structure-review",
        "status": "进行中",
        "phase": "独立任务",
        "assignee": "",
        "updatedAt": "2026-07-13T05:50:57.223436+00:00",
        "tags": [],
        "source": "filesystem",
        "hidden": False
    },
    {
        "taskId": "projects-directory-reorg",
        "title": "Projects Directory 整理与重构",
        "parentProjectId": "projects-directory-reorg",
        "parentProjectName": "Projects Directory 整理与重构",
        "workspacePath": "F:\\1AI\\Agent control center\\projects",
        "status": "已完成",
        "phase": "已归档",
        "assignee": "项目调度官",
        "updatedAt": "2026-07-13T17:47:00+08:00",
        "tags": ["目录整理", "项目合并", "task_directory", "projects_index", "清理"],
        "source": "initiative",
        "hidden": False
    },
    {
        "taskId": "projects-directory-reorg-2",
        "title": "Projects Directory 整理与重构",
        "parentProjectId": "projects-directory-reorg",
        "parentProjectName": "Projects Directory 整理与重构",
        "workspacePath": "F:\\1AI\\Agent control center\\projects\\archive",
        "status": "已完成",
        "phase": "执行整理 + 执行后验证 + 归档",
        "assignee": "",
        "updatedAt": "2026-07-13",
        "tags": ["目录整理", "项目合并", "task_directory", "projects_index", "清理", "归档"],
        "source": "projects_index",
        "hidden": False
    },
    {
        "taskId": "agent-control-center-optimization-v1-0-archive-20260626",
        "title": "Phase 3+4",
        "parentProjectId": "agent-control-center-optimization",
        "parentProjectName": "Agent Control Center 优化",
        "workspacePath": "F:\\1AI\\Agent control center",
        "status": "已归档",
        "phase": "Phase 3+4",
        "assignee": "",
        "updatedAt": "2026-06-26",
        "tags": ["前端拆分", "测试补全", "Calendar正则", "Agent Control Center"],
        "source": "projects_index",
        "hidden": False
    },
    {
        "taskId": "agent-control-center-optimization-v2-0-archive-20260626",
        "title": "Phase 5: 技术债清理",
        "parentProjectId": "agent-control-center-optimization",
        "parentProjectName": "Agent Control Center 优化",
        "workspacePath": "F:\\1AI\\Agent control center",
        "status": "已归档",
        "phase": "Phase 5: 技术债清理",
        "assignee": "",
        "updatedAt": "2026-06-26",
        "tags": ["技术债", "lifespan", "日志API", "ErrorResponse", "Agent Control Center"],
        "source": "projects_index",
        "hidden": False
    },
    {
        "taskId": "agent-control-center-optimization-v3-0-archive-20260626",
        "title": "Phase 7: 监控与文档（最终阶段）",
        "parentProjectId": "agent-control-center-optimization",
        "parentProjectName": "Agent Control Center 优化",
        "workspacePath": "F:\\1AI\\Agent control center",
        "status": "已完成",
        "phase": "Phase 7: 监控与文档（最终阶段）",
        "assignee": "",
        "updatedAt": "2026-06-26",
        "tags": ["Prometheus", "metrics", "API文档", "运维手册", "端口修复", "Agent Control Center", "最终归档"],
        "source": "projects_index",
        "hidden": False
    },
    {
        "taskId": "chip-startup-kpi-incentive-v1-0-archive-20260629",
        "title": "Phase 1: 框架文档",
        "parentProjectId": "archive",
        "parentProjectName": "archive",
        "workspacePath": "F:\\1AI\\Agent control center\\projects\\archive\\芯片初创公司管理层KPI激励方案",
        "status": "已完成",
        "phase": "Phase 1: 框架文档",
        "assignee": "",
        "updatedAt": "2026-06-29",
        "tags": ["KPI激励方案", "芯片初创公司", "框架文档", "平衡计分卡", "OKR+KPI", "Phase 1"],
        "source": "projects_index",
        "hidden": False
    },
    {
        "taskId": "chip-startup-kpi-incentive-v2-0-archive-20260629",
        "title": "Phase 2: 核心方案文档（CTO激励+新成员激励+股权管控）",
        "parentProjectId": "archive",
        "parentProjectName": "archive",
        "workspacePath": "F:\\1AI\\Agent control center\\projects\\archive\\芯片初创公司管理层KPI激励方案",
        "status": "已完成",
        "phase": "Phase 2: 核心方案文档",
        "assignee": "",
        "updatedAt": "2026-06-29",
        "tags": ["KPI激励方案", "芯片初创公司", "CTO激励", "新成员激励", "股权管控", "AB股", "Phase 2"],
        "source": "projects_index",
        "hidden": False
    },
    {
        "taskId": "chip-startup-kpi-incentive-v3-0-archive-20260629",
        "title": "Phase 3: CXO激励方案（含返工闭环）",
        "parentProjectId": "archive",
        "parentProjectName": "archive",
        "workspacePath": "F:\\1AI\\Agent control center\\projects\\archive\\芯片初创公司管理层KPI激励方案",
        "status": "已完成",
        "phase": "Phase 3: CXO激励方案（含返工闭环）",
        "assignee": "",
        "updatedAt": "2026-06-29",
        "tags": ["KPI激励方案", "芯片初创公司", "CXO激励", "返工闭环", "五级阶梯", "Phase 3"],
        "source": "projects_index",
        "hidden": False
    },
    {
        "taskId": "calculator-test-20260629-231257-v1-0-archive-20260630",
        "title": "全链路协作测试",
        "parentProjectId": "calculator-test-20260629-231257",
        "parentProjectName": "calculator-test-20260629-231257",
        "workspacePath": "F:\\1AI\\Agent control center\\projects\\calculator-test-20260629-231257",
        "status": "已完成",
        "phase": "全链路协作测试",
        "assignee": "",
        "updatedAt": "2026-07-13T12:30:07.071982+00:00",
        "tags": ["计算器", "协作测试", "全链路", "零缺陷"],
        "source": "projects_index",
        "hidden": True
    },
    {
        "taskId": "task-skill-upgrade-20260630-v1-0-archive-20260630",
        "title": "全链路 Skill 体系升级（Track A/B/C/D）",
        "parentProjectId": "task-skill-upgrade-20260630",
        "parentProjectName": "Multiagent Skill Upgrade (TASK-SKILL-UPGRADE-20260630)",
        "workspacePath": "F:\\1AI\\Agent control center\\docs\\multiagent-skill-upgrade-plan.md",
        "status": "已归档",
        "phase": "全链路 Skill 体系升级（Track A/B/C/D）",
        "assignee": "",
        "updatedAt": "2026-06-30",
        "tags": ["Skill升级", "A2A协议", "多智能体协作", "隐私安全", "Python-First", "角色边界", "TASK-SKILL-UPGRADE"],
        "source": "projects_index",
        "hidden": False
    },
    {
        "taskId": "task-runtime-prompt-verify-20260630-v2-0-archive-20260630",
        "title": "P1 返工闭环 — 运维复验 + 质量复审全部通过",
        "parentProjectId": "task-runtime-prompt-verify-20260630",
        "parentProjectName": "Runtime Prompt 一致性只读复验",
        "workspacePath": "E:\\openclaw\\clawclaw\\.openclaw\\workspace\\IDENTITY.md",
        "status": "已归档",
        "phase": "P1 返工闭环 — 运维复验 + 质量复审全部通过",
        "assignee": "",
        "updatedAt": "2026-06-30",
        "tags": ["P1返工闭环", "只读复验", "Runtime验证", "@规则一致性", "隐私审计补充", "零真实ID泄漏"],
        "source": "projects_index",
        "hidden": False
    },
    {
        "taskId": "phase1-agent-health-monitor-v1-0-archive-20260630",
        "title": "方案规划（三审）→ 开发实现 → 返工修复 → 运维验证 → 质量审计",
        "parentProjectId": "agent-evolution",
        "parentProjectName": "agent-evolution",
        "workspacePath": "F:\\1AI\\Agent control center\\projects\\agent-evolution\\phase1-health-monitor",
        "status": "已归档",
        "phase": "方案规划（三审）→ 开发实现 → 返工修复 → 运维验证 → 质量审计",
        "assignee": "",
        "updatedAt": "2026-06-30",
        "tags": ["Agent进化", "Phase 1", "健康监控", "探活脚本", "P0告警", "只读不干预"],
        "source": "projects_index",
        "hidden": False
    },
    {
        "taskId": "phase2-config-conflict-detection-v1-0-archive-20260630",
        "title": "方案规划（三审）→ 开发实现 → 返工修复 → 文档修补 → 运维验证 → 质量审计",
        "parentProjectId": "agent-evolution",
        "parentProjectName": "agent-evolution",
        "workspacePath": "F:\\1AI\\Agent control center\\projects\\agent-evolution\\phase2-config-conflict",
        "status": "已归档",
        "phase": "方案规划（三审）→ 开发实现 → 返工修复 → 文档修补 → 运维验证 → 质量审计",
        "assignee": "",
        "updatedAt": "2026-06-30",
        "tags": ["Agent进化", "Phase 2", "配置冲突检测", "AppID唯一性", "端口冲突", "数据安全"],
        "source": "projects_index",
        "hidden": False
    },
    {
        "taskId": "phase4-privacy-scan-v1-0-archive-20260630",
        "title": "方案规划（三审含阻塞补充）→ 开发 → 返工 → README补充 → 运维验证 → 质量审计",
        "parentProjectId": "agent-evolution",
        "parentProjectName": "agent-evolution",
        "workspacePath": "F:\\1AI\\Agent control center\\projects\\agent-evolution\\phase4-privacy-scan",
        "status": "已归档",
        "phase": "方案规划（三审含阻塞补充）→ 开发 → 返工 → README补充 → 运维验证 → 质量审计",
        "assignee": "",
        "updatedAt": "2026-06-30",
        "tags": ["Agent进化", "Phase 4", "隐私扫描", "敏感信息检测", "SHA256指纹", "appSecret"],
        "source": "projects_index",
        "hidden": False
    },
    {
        "taskId": "config-and-routing-modules-v1-0-archive-20260709",
        "title": "Phase 1: 配置中心（已归档）",
        "parentProjectId": "config-and-routing-modules",
        "parentProjectName": "Agent Control Center — Phase 1: 配置中心",
        "workspacePath": "F:\\1AI\\Agent control center\\src\\feishu_stack\\modules\\config_center\\router.py",
        "status": "已归档",
        "phase": "Phase 1: 配置中心（已归档）",
        "assignee": "",
        "updatedAt": "2026-07-09",
        "tags": ["配置中心", "Agent Control Center", "Phase 1", "已归档"],
        "source": "projects_index",
        "hidden": False
    },
    {
        "taskId": "config-and-routing-modules-v2-0-archive-20260709",
        "title": "Phase 2-4: 路由+Webhook+飞书连接",
        "parentProjectId": "config-and-routing-modules",
        "parentProjectName": "Agent Control Center — Phase 2-4: 路由+Webhook+飞书连接",
        "workspacePath": "F:\\1AI\\Agent control center",
        "status": "已归档",
        "phase": "Phase 2-4: 路由+Webhook+飞书连接",
        "assignee": "",
        "updatedAt": "2026-07-09",
        "tags": ["路由模块", "Webhook", "飞书连接", "Phase 2-4"],
        "source": "projects_index",
        "hidden": False
    },
    {
        "taskId": "company-doc-review-20260710-v1-0-archive-20260710",
        "title": "公司架构分析审计（返工闭环+已归档）",
        "parentProjectId": "company-doc-review-20260710",
        "parentProjectName": "芯智呈光公司资料整理与优化方案",
        "workspacePath": "F:\\1AI\\Agent control center\\projects\\archive\\company-structure-review",
        "status": "已归档",
        "phase": "公司架构分析审计（返工闭环+已归档）",
        "assignee": "",
        "updatedAt": "2026-07-10",
        "tags": ["公司资料", "差异化发展战略", "公司架构", "协议文件", "分析报告", "返工闭环"],
        "source": "projects_index",
        "hidden": False
    },
    {
        "taskId": "config-center-knowledge-base-v1-0-archive-20260710",
        "title": "方案规划（审计通过+已归档）",
        "parentProjectId": "agent-control-center-optimization",
        "parentProjectName": "Agent Control Center 优化",
        "workspacePath": "F:\\1AI\\Agent control center",
        "status": "已归档",
        "phase": "方案规划（审计通过+已归档）",
        "assignee": "",
        "updatedAt": "2026-07-10",
        "tags": ["配置中心", "知识库", "本地方案", "防泄密", "Agent Control Center"],
        "source": "projects_index",
        "hidden": False
    },
    {
        "taskId": "phase-feishu-connection-v1-0-archive-20260709",
        "title": "飞书连接模块开发（已归档）",
        "parentProjectId": "phase-feishu-connection",
        "parentProjectName": "飞书连接模块开发",
        "workspacePath": "F:\\1AI\\Agent control center",
        "status": "已归档",
        "phase": "飞书连接模块开发（已归档）",
        "assignee": "",
        "updatedAt": "2026-07-09",
        "tags": ["飞书连接", "Agent Control Center", "已归档"],
        "source": "projects_index",
        "hidden": False
    },
    {
        "taskId": "phase3-task-dashboard-v1-0-archive-20260708",
        "title": "Phase 3: 任务状态仪表盘HTML（已归档）",
        "parentProjectId": "agent-evolution",
        "parentProjectName": "agent-evolution",
        "workspacePath": "F:\\1AI\\Agent control center\\projects\\agent-evolution\\phase3-task-dashboard",
        "status": "已归档",
        "phase": "Phase 3: 任务状态仪表盘HTML（已归档）",
        "assignee": "",
        "updatedAt": "2026-07-08",
        "tags": ["Agent进化", "Phase 3", "任务仪表盘", "HTML", "已归档"],
        "source": "projects_index",
        "hidden": False
    },
    {
        "taskId": "phase3-task-dashboard-v2-0-archive-20260708",
        "title": "PHASE3-CONTROL-CENTER-MERGE（已归档）",
        "parentProjectId": "agent-evolution",
        "parentProjectName": "agent-evolution",
        "workspacePath": "F:\\1AI\\Agent control center",
        "status": "已归档",
        "phase": "PHASE3-CONTROL-CENTER-MERGE（已归档）",
        "assignee": "",
        "updatedAt": "2026-07-08",
        "tags": ["Agent进化", "Phase 3", "Control Center集成", "已归档"],
        "source": "projects_index",
        "hidden": False
    },
    {
        "taskId": "phase5-skill-registry-v1-0-archive-20260708",
        "title": "Phase 5: Skill 版本统一管理（已归档）",
        "parentProjectId": "agent-evolution",
        "parentProjectName": "agent-evolution",
        "workspacePath": "F:\\1AI\\Agent control center\\projects\\agent-evolution\\phase5-skill-registry",
        "status": "已归档",
        "phase": "Phase 5: Skill 版本统一管理（已归档）",
        "assignee": "",
        "updatedAt": "2026-07-08",
        "tags": ["Agent进化", "Phase 5", "Skill Registry", "版本管理", "已归档"],
        "source": "projects_index",
        "hidden": False
    },
    {
        "taskId": "phase6-regression-test-v1-0-archive-20260708",
        "title": "Phase 6: 回归测试迁移（已归档）",
        "parentProjectId": "agent-evolution",
        "parentProjectName": "agent-evolution",
        "workspacePath": "F:\\1AI\\Agent control center\\projects\\agent-evolution",
        "status": "已归档",
        "phase": "Phase 6: 回归测试迁移（已归档）",
        "assignee": "",
        "updatedAt": "2026-07-08",
        "tags": ["Agent进化", "Phase 6", "回归测试", "已归档"],
        "source": "projects_index",
        "hidden": False
    },
    {
        "taskId": "phase1-acc-task-dashboard-v1-0-archive-20260708",
        "title": "Phase 1: ACC Task Dashboard（已归档）",
        "parentProjectId": "agent-evolution",
        "parentProjectName": "agent-evolution",
        "workspacePath": "F:\\1AI\\Agent control center",
        "status": "已归档",
        "phase": "Phase 1: ACC Task Dashboard（已归档）",
        "assignee": "",
        "updatedAt": "2026-07-08",
        "tags": ["Agent进化", "ACC", "Task Dashboard", "已归档"],
        "source": "projects_index",
        "hidden": False
    },
    {
        "taskId": "access-check-list-v1-0-archive-20260709",
        "title": "权限准入检查清单设计（已归档）",
        "parentProjectId": "access-check-list",
        "parentProjectName": "权限准入检查清单设计",
        "workspacePath": "F:\\1AI\\Agent control center",
        "status": "已归档",
        "phase": "权限准入检查清单设计（已归档）",
        "assignee": "",
        "updatedAt": "2026-07-09",
        "tags": ["权限准入", "检查清单", "已归档"],
        "source": "projects_index",
        "hidden": False
    },
    {
        "taskId": "feishu-agent-discussion-v1-0-archive-20260709",
        "title": "飞书Agent整体优化讨论（已归档）",
        "parentProjectId": "acc-feishu-agent-optimization-discussion",
        "parentProjectName": "飞书Agent优化讨论",
        "workspacePath": "F:\\1AI\\Agent control center",
        "status": "已归档",
        "phase": "飞书Agent整体优化讨论（已归档）",
        "assignee": "",
        "updatedAt": "2026-07-09",
        "tags": ["飞书Agent", "优化讨论", "已归档"],
        "source": "projects_index",
        "hidden": False
    },
    {
        "taskId": "feishu-connection-token-check-v1-0-archive-20260709",
        "title": "飞书连接Token校验（已归档）",
        "parentProjectId": "feishu-connection-token-check",
        "parentProjectName": "飞书连接Token校验",
        "workspacePath": "F:\\1AI\\Agent control center",
        "status": "已归档",
        "phase": "飞书连接Token校验（已归档）",
        "assignee": "",
        "updatedAt": "2026-07-09",
        "tags": ["飞书连接", "Token校验", "已归档"],
        "source": "projects_index",
        "hidden": False
    },
    {
        "taskId": "mmi-inverse-design-survey-v1-0-archive-20260713",
        "title": "Phase 1: 开发 + 验证 + 审计 + 归档",
        "parentProjectId": "mmi-inverse-design-survey",
        "parentProjectName": "mmi-inverse-design-survey",
        "workspacePath": "F:\\1AI\\Agent control center\\projects\\mmi-inverse-design-survey",
        "status": "已完成",
        "phase": "Phase 1: 开发 + 验证 + 审计 + 归档",
        "assignee": "",
        "updatedAt": "2026-07-13",
        "tags": ["MMI", "FDTD", "逆向设计", "伴随法", "Phase 1", "任意分光比", "硅基光子学", "方案设计"],
        "source": "projects_index",
        "hidden": False
    },
    {
        "taskId": "mmi-inverse-design-survey-phase2",
        "title": "Phase 2: FDTD仿真实现与优化执行 — 1:99分光比MMI逆向设计",
        "parentProjectId": "mmi-inverse-design-survey",
        "parentProjectName": "任意分光比MMI逆向设计方案文献调研",
        "workspacePath": "F:\\1AI\\Agent control center\\projects\\mmi-inverse-design-survey",
        "status": "已完成",
        "phase": "Phase 2: 开发 → 返工(源位置/Z监视器) → 运维验证 → 质量审计通过 → 已归档",
        "assignee": "运维验证官",
        "updatedAt": "2026-07-14T21:57:00+08:00",
        "tags": ["FDTD", "MMI", "逆向设计", "Phase 2", "伴随法", "优化脚本", "1:99分光比"],
        "source": "initiative",
        "hidden": False
    },
    {
        "taskId": "chip-spectrometer-report",
        "title": "芯片光谱仪商业化研究报告（60页Word文档）",
        "parentProjectId": "chip-spectrometer-report",
        "parentProjectName": "芯片光谱仪商业化研究报告",
        "workspacePath": "F:\\1AI\\Agent control center\\projects\\chip-spectrometer-report",
        "status": "已完成",
        "phase": "十章节全文内容编写 + P1返工修复 + 60页Word汇编（已归档）",
        "assignee": "项目调度官",
        "updatedAt": "2026-07-14T11:40:00+08:00",
        "tags": ["芯片光谱仪", "商业化", "行业报告", "市场分析", "60页Word", "已归档"],
        "source": "initiative",
        "hidden": False
    },
    {
        "taskId": "chip-spectrometer-report-v1-1-archive-20260714",
        "title": "Word完善修复: 清除md残迹/任务用语 + 插入5张图表",
        "parentProjectId": "chip-spectrometer-report",
        "parentProjectName": "chip-spectrometer-report",
        "workspacePath": "F:\\1AI\\Agent control center\\projects\\chip-spectrometer-report",
        "status": "已完成",
        "phase": "Word完善修复",
        "assignee": "",
        "updatedAt": "2026-07-14",
        "tags": ["芯片光谱仪", "商业化", "行业报告", "市场分析", "60页Word"],
        "source": "projects_index",
        "hidden": False
    },
    {
        "taskId": "mmi-inverse-design-survey-phase2-v1-0-phase2-20260714",
        "title": "Phase 2: 开发 + 返工修复(源位置/Z监视器) + 运维验证 + 质量审计通过 + 可归档",
        "parentProjectId": "mmi-inverse-design-survey",
        "parentProjectName": "mmi-inverse-design-survey",
        "workspacePath": "F:\\1AI\\Agent control center\\projects\\mmi-inverse-design-survey\\simulation",
        "status": "已完成",
        "phase": "Phase 2: 开发 + 返工修复 + 运维验证 + 质量审计通过 + 可归档",
        "assignee": "",
        "updatedAt": "2026-07-14",
        "tags": ["MMI", "FDTD", "逆向设计", "伴随法", "Phase 2", "1:99分光比", "硅基光子学", "源位置修复", "Z横截面监视器"],
        "source": "projects_index",
        "hidden": False
    },
    {
        "taskId": "chip-spectrometer-integration-why",
        "title": "光芯片光通信与光传感集成片上光谱仪必要性调研",
        "parentProjectId": "chip-spectrometer-report",
        "parentProjectName": "芯片光谱仪商业化研究报告",
        "workspacePath": "F:\\1AI\\Agent control center\\projects\\chip-spectrometer-report",
        "status": "已完成",
        "phase": "Phase 5: 项目归档",
        "assignee": "项目调度官",
        "updatedAt": "2026-07-15T15:40:00+08:00",
        "tags": ["片上光谱仪", "光通信", "光传感", "集成必要性", "文献调研", "Phase 1"],
        "source": "initiative",
        "hidden": False
    },
    {
        "taskId": "feishu-connection-grid-test",
        "title": "飞书连接Grid测试",
        "parentProjectId": "feishu-connection-grid-test",
        "parentProjectName": "飞书连接Grid测试",
        "workspacePath": "F:\\1AI\\Agent control center",
        "status": "已完成",
        "phase": "飞书连接Grid测试",
        "assignee": "",
        "updatedAt": "2026-07-12T09:39:00+08:00",
        "tags": ["飞书连接", "Grid测试"],
        "source": "initiative",
        "hidden": False
    },
    {
        "taskId": "mmi-inverse-design-survey-phase3",
        "title": "Phase 3: FDTD 1:99 分光比 MMI 逆向设计优化执行",
        "parentProjectId": "mmi-inverse-design-survey",
        "parentProjectName": "任意分光比MMI逆向设计方案文献调研",
        "workspacePath": "F:\\1AI\\Agent control center\\projects\\mmi-inverse-design-survey\\simulation",
        "status": "已完成",
        "phase": "Phase 3: FDTD 1:99 分光比 MMI 逆向设计优化执行",
        "assignee": "",
        "updatedAt": "2026-07-15T16:09:00+08:00",
        "tags": ["FDTD", "MMI", "逆向设计", "Phase 3", "1:99分光比"],
        "source": "initiative",
        "hidden": False
    },
    {
        "taskId": "chip-spectrometer-integration-why-phase2",
        "title": "光芯片光通信与光传感集成片上光谱仪必要性调研Phase 2",
        "parentProjectId": "chip-spectrometer-report",
        "parentProjectName": "芯片光谱仪商业化研究报告",
        "workspacePath": "F:\\1AI\\Agent control center\\projects\\chip-spectrometer-report",
        "status": "已完成",
        "phase": "Phase 3: 项目归档",
        "assignee": "",
        "updatedAt": "2026-07-15T16:18:00+08:00",
        "tags": ["片上光谱仪", "光通信", "光传感", "集成必要性", "Phase 2"],
        "source": "initiative",
        "hidden": False
    },
    {
        "taskId": "multi-agent-document-battlefield",
        "title": "Multi-Agent 文档战场",
        "parentProjectId": "multi-agent-document-battlefield",
        "parentProjectName": "Multi-Agent 文档战场",
        "workspacePath": "F:\\1AI\\Agent control center",
        "status": "已完成",
        "phase": "文档战场开发",
        "assignee": "",
        "updatedAt": "2026-07-16T11:40:40+08:00",
        "tags": ["文档战场", "Multi-Agent"],
        "source": "initiative",
        "hidden": False
    },
    {
        "taskId": "mmi-inverse-design-phase4",
        "title": "Phase 4: FDTD 1:99 分光比 MMI 逆向设计优化执行 + 全流程归档",
        "parentProjectId": "mmi-inverse-design-survey",
        "parentProjectName": "任意分光比MMI逆向设计方案文献调研",
        "workspacePath": "F:\\1AI\\Agent control center\\projects\\mmi-inverse-design-survey\\simulation",
        "status": "已完成",
        "phase": "Phase 4: 全流程归档",
        "assignee": "",
        "updatedAt": "2026-07-16T17:04:00+08:00",
        "tags": ["FDTD", "MMI", "逆向设计", "Phase 4", "1:99分光比"],
        "source": "initiative",
        "hidden": False
    },
    {
        "taskId": "xzc-chatbot-upgrade-v2",
        "title": "芯智呈光ChatBot升级V2 - 飞书文档知识库串联",
        "parentProjectId": "xzc-chatbot-upgrade-v2",
        "parentProjectName": "芯智呈光ChatBot升级V2",
        "workspacePath": "F:\\1AI\\Agent control center",
        "status": "已完成",
        "phase": "代码实现 + 自测 + 运维验证 + 质量审计 + 归档",
        "assignee": "",
        "updatedAt": "2026-07-17T18:48:00+08:00",
        "tags": ["ChatBot", "知识库", "飞书文档", "芯智呈光"],
        "source": "initiative",
        "hidden": False
    }
]

doc = {
    "version": 1,
    "projectsRoot": "F:\\1AI\\Agent control center\\projects",
    "updatedAt": "2026-07-20T05:46:00.000000+00:00",
    "tasks": tasks
}

output_path = "F:\\1AI\\Agent control center\\projects\\task_directory.json"
with open(output_path, "w", encoding="utf-8") as f:
    json.dump(doc, f, ensure_ascii=False, indent=2)

print(f"Restored {len(tasks)} tasks successfully!")
print(f"Validated JSON: {json.dumps(doc, ensure_ascii=False)[:50]}...")
